DELETE http://localhost:3003/api/blogs/69080e0d7a7c56a57fc9da05
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNhcmwgZ3JpbWVzIiwiaWQiOiI2OTA4MGE3M2VmY2RlYjZlMjk3ZjUxNDUiLCJpYXQiOjE3NjIxMzc3MDAsImV4cCI6MTc2MjE0MTMwMH0.JWw-6o84t7IGVUNV6xf3k8ois8zKSgmW_76V3eAlbkE
