GET http://localhost:3003/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNhcmwgZ3JpbWVzIiwiaWQiOiI2OTA4MGE3M2VmY2RlYjZlMjk3ZjUxNDUiLCJpYXQiOjE3NjIzMDQxMTYsImV4cCI6MTc2MjMwNzcxNn0.bsj0o08woKZ29jTjo3Aq4YBlI7VPLxZekYMN1epmWFU